### ISSUE TITLE
How to reenact?

### ISSUE THREAD

**Issue by Woomou** [chiehwangs/gaussian-head#10]
I didn't see a direct interface for reenactment, but I did see it in the project demonstration. Where is this feature located in the code?

**Comment by chiehwangs** [comment]
> I didn't see a direct interface for reenactment, but I did see it in the project demonstration. Where is this feature located in the code?

Hi,

[issue](https://github.com/chiehwangs/gaussian-head/issues/5) may help you. In addition, reenactment requires additional code changes. If necessary, you can contact me by email.
