### ISSUE TITLE
when render loading training cameras, automatic quit

### ISSUE THREAD

**Issue by westwind027** [chiehwangs/gaussian-head#12]
<img width="466" alt="image" src="https://github.com/chiehwangs/gaussian-head/assets/9116046/8003f4cc-2e7e-43bb-a680-99889764467f">

**Comment by chiehwangs** [comment]
> <img alt="image" width="466" src="https://private-user-images.githubusercontent.com/9116046/298335374-8003f4cc-2e7e-43bb-a680-99889764467f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTU5MTMsIm5iZiI6MTcwNTgxNTYxMywicGF0aCI6Ii85MTE2MDQ2LzI5ODMzNTM3NC04MDAzZjRjYy0yZTdlLTQzYmItYTY4MC05OTg4OTc2NDQ2N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDU0MDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0NGE0NDQ3OWFjMDMwN2Y4NDcxM2E4OWFiYjhjN2UzZGU2MjE0ZGFlY2NjMzJjYzYwNzljMzE0MTdhMDAxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.adfK7AQUu33mfeir0vzBr9I09E-ut8-xHKht-Cl9k4M">

Hi, 

The possible reason is RAM limitation causes the process to be killed. 

We load the training data into the memory at one time before training to reduce the communication time between CPU and storage during training. For 2000 frames, this may require more than 24GB of memory. Therefore, you can try reducing images; or, try using `dataloader` to load images during training.
