### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Store'

### ISSUE THREAD

**Issue by liuwing** [chiehwangs/gaussian-head#14]
when I use render.py,Looking for config file in ./output/id1/cfg_args
Config file found: ./output/id1/cfg_args
Rendering ./output/id1/
Traceback (most recent call last):
  File "render.py", line 97, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.warm_up, args.is_debug, args.skip_train, args.skip_test, 
  File "render.py", line 48, in render_sets
    scene = Scene(dataset, gaussians, is_debug=is_debug, novel_view=novel_view, only_head=only_head, load_iteration=iteration, shuffle=False)
  File "/data/liukean/projects/gaussian-head/scene/__init__.py", line 25, in __init__
    self.loaded_iter = searchForMaxIteration(os.path.join(self.model_path, "point_cloud"))
  File "/data/liukean/projects/gaussian-head/utils/system_utils.py", line 29, in searchForMaxIteration
    saved_iters = [int(fname.split("_")[-1]) for fname in os.listdir(folder)]
  File "/data/liukean/projects/gaussian-head/utils/system_utils.py", line 29, in <listcomp>
    saved_iters = [int(fname.split("_")[-1]) for fname in os.listdir(folder)]
ValueError: invalid literal for int() with base 10: 'Store'
<img width="1037" alt="截屏2024-01-24 10 22 09" src="https://github.com/chiehwangs/gaussian-head/assets/46471818/debfe872-ed52-437e-a759-fb44d5923fc9">

**Comment by chiehwangs** [comment]
> when I use render.py,Looking for config file in ./output/id1/cfg_args Config file found: ./output/id1/cfg_args Rendering ./output/id1/ Traceback (most recent call last): File "render.py", line 97, in render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.warm_up, args.is_debug, args.skip_train, args.skip_test, File "render.py", line 48, in render_sets scene = Scene(dataset, gaussians, is_debug=is_debug, novel_view=novel_view, only_head=only_head, load_iteration=iteration, shuffle=False) File "/data/liukean/projects/gaussian-head/scene/**init**.py", line 25, in **init** self.loaded_iter = searchForMaxIteration(os.path.join(self.model_path, "point_cloud")) File "/data/liukean/projects/gaussian-head/utils/system_utils.py", line 29, in searchForMaxIteration saved_iters = [int(fname.split("_")[-1]) for fname in os.listdir(folder)] File "/data/liukean/projects/gaussian-head/utils/system_utils.py", line 29, in saved_iters = [int(fname.split("_")[-1]) for fname in os.listdir(folder)] ValueError: invalid literal for int() with base 10: 'Store' <img alt="截屏2024-01-24 10 22 09" width="1037" src="https://private-user-images.githubusercontent.com/46471818/299157485-debfe872-ed52-437e-a759-fb44d5923fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTkyNzgsIm5iZiI6MTcwNjA5ODk3OCwicGF0aCI6Ii80NjQ3MTgxOC8yOTkxNTc0ODUtZGViZmU4NzItZWQ1Mi00MzdlLWE3NTktZmI0NGQ1OTIzZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMzFiZjQ2N2QyNGVmMjY3MDAwYTYwN2Y1YzMzYmQxOTk3MTM3MWM4NjY5ZjgyMjAxZDM1ZmVmMDU5YWZjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H-EUGtmgzFi0-ADBusmJZJI4f_95Yt2Qx4i9pVk0EBQ">

Hi,

This should be a path error. `loaded_iter` did not read the pre-trained model from the correct place. Please ensure that the path is consistent with the requirements of our git page. If it still does not work, please continue to ask here.
