### ISSUE TITLE
head dataset

### ISSUE THREAD

**Issue by yangshubin123** [chiehwangs/gaussian-head#17]
How to create a dataset of my head for training？

**Comment by chiehwangs** [comment]
> How to create a dataset of my head for training？

Hi, 

In order to make a fair and convenient comparison, we did not introduce additional new dataset, all videos come from public `NeRFBlendShape`, refer to https://github.com/chiehwangs/gaussian-head/issues/7 and [NeRFBlendShape](https://ustc3dv.github.io/NeRFBlendShape/)

**Comment by chiehwangs** [comment]
Refer to AD-NeRF, it works well.
