### ISSUE TITLE
Why can't I render different head posture orientations?

### ISSUE THREAD

**Issue by gaga0714** [chiehwangs/gaussian-head#19]
Hello, I want to try to render different head pose orientations, but when I try to render the pre-trained model you provided using each of the following three commands, I get the same result head orientation, can you give me some suggestions?
`python render.py --novel_view 5 -m ./output/id1`
`python render.py --novel_view 30 -m ./output/id1`
`python render.py --novel_view 50 -m ./output/id1`

**Comment by chiehwangs** [comment]
> Hello, I want to try to render different head pose orientations, but when I try to render the pre-trained model you provided using each of the following three commands, I get the same result head orientation, can you give me some suggestions? `python render.py --novel_view 5 -m ./output/id1` `python render.py --novel_view 30 -m ./output/id1` `python render.py --novel_view 50 -m ./output/id1`

Hi,

I guess the number you write after  `--novel_view` is to express the angle of rotation? In fact, you only need to set `--novel_view` to `True` to render the new perspective. The specific angle settings of the new perspective are in `L170~L178` of the `dataset_readers.py`.

**Comment by gaga0714** [comment]
> > Hello, I want to try to render different head pose orientations, but when I try to render the pre-trained model you provided using each of the following three commands, I get the same result head orientation, can you give me some suggestions? `python render.py --novel_view 5 -m ./output/id1` `python render.py --novel_view 30 -m ./output/id1` `python render.py --novel_view 50 -m ./output/id1`
> 
> Hi,
> 
> I guess the number you write after `--novel_view` is to express the angle of rotation? In fact, you only need to set `--novel_view` to `True` to render the new perspective. The specific angle settings of the new perspective are in `L170~L178` of the `dataset_readers.py`.

Thank you very much, I did misunderstand the meaning of the parameter after `--novel_view`, and now I can set the different head pose orientations with the code in `dataset_readers.py`.
