### ISSUE TITLE
time 

### ISSUE THREAD

**Issue by Tiandishihua** [chiehwangs/gaussian-head#20]
How long the infering time is？

**Comment by chiehwangs** [comment]
> How long the infering time is？

Hi,

Rendering one takes about 0.1 seconds on my computing platform (ubuntu20.04, RTX3090 24GB and inter i9-13900k 32GB) and about 0.13 seconds on ubuntu20.04, RTX2080ti 12GB and inter i7-12900k 32GB)

Best,
