### ISSUE TITLE
What's the specific setting for dividing the trainset and the testset?

### ISSUE THREAD

**Issue by zydmu123** [chiehwangs/gaussian-head#21]
First, thanks for your great work, and I'd like to know the the specific setting for the trainset and the testset of each id?

As the paper mentioned:
> _The training data we use for each subject consists of approximately 2000 frames, and evaluate the results using the last 200 frames._

While the number of every id is  range of 3000~4200 frames. is the trainset the first 2000 frames and the last 200 frames of the datas as the testset?

**Comment by chiehwangs** [comment]
> First, thanks for your great work, and I'd like to know the the specific setting for the trainset and the testset of each id?
> 
> As the paper mentioned:
> 
> > _The training data we use for each subject consists of approximately 2000 frames, and evaluate the results using the last 200 frames._
> 
> While the number of every id is range of 3000~4200 frames. is the trainset the first 2000 frames and the last 200 frames of the datas as the testset?

Hi,

You are right. Although the video of each ID contains more than 2000 frames (30fps), we only take the first ～2000 frames for training. For the testset, we take the number stated in the paper from back to front and all comparison methods follow this Setting. As for the middle frames, we do Regardless.

Additionally, we uploaded an updated arXiv version.

best,

**Comment by chiehwangs** [comment]
> > First, thanks for your great work, and I'd like to know the the specific setting for the trainset and the testset of each id?
> > As the paper mentioned:
> > > _The training data we use for each subject consists of approximately 2000 frames, and evaluate the results using the last 200 frames._
> > 
> > 
> > While the number of every id is range of 3000~4200 frames. is the trainset the first 2000 frames and the last 200 frames of the datas as the testset?
> 
> Hi,
> 
> You are right. Although the video of each ID contains more than 2000 frames (30fps), we only take the first ～2000 frames for training. For the testset, we take the number stated in the paper from back to front and all comparison method and all comparison methods follow this Setting. As for the middle frames, we do not Regardless.
> 
> best,

**Comment by zydmu123** [comment]
Thanks for your reply! I just read the updated arXiv paper,  it says:
> The training data for each subject comprised approximately 2000 to 2500 frames, and the test data was conducted using the last 3% to 5% of frames.

Does it means the specific setting for the trainset and the testset of each id is the same as that of the old arXiv version?

**Comment by chiehwangs** [comment]
> Thanks for your reply! I just read the updated arXiv paper, it says:
> 
> > The training data for each subject comprised approximately 2000 to 2500 frames, and the test data was conducted using the last 3% to 5% of frames.
> 
> Does it means the specific setting for the trainset and the testset of each id is the same as that of the old arXiv version?

Hi,

We did additional experiments later, and all settings were in accordance with the latest paper ~

best,

**Comment by MatthewLeony** [comment]
Hi@chiehwangs, I'm also interested in the specific setting of training dataset for the sake of methods' comparison, could you make it more clear for the exact frames of trainset and testset of each id in the new paper? Thanks a lot!
