### ISSUE TITLE
Some questions about the code.

### ISSUE THREAD

**Issue by gaga0714** [chiehwangs/gaussian-head#26]
Hi, when I use your model for training, there report an error:
`The size of tensor a (9) must match the size of tensor b (3) at non-singleton dimension 1`
![image](https://github.com/chiehwangs/gaussian-head/assets/140368447/15bade0f-2441-41f7-ae53-46d35f75c753)
I wonder if this line of code may be changed from `if input.shape[1] != 3:` to `if input.shape[0] != 3:`?
![image](https://github.com/chiehwangs/gaussian-head/assets/140368447/b156d2a0-835d-4618-821c-439aa745bcf6)
I really hope you can give me an answer, thank you!

**Comment by ZardYuan** [comment]
I guess the shape of render-output is (c,h,w), while the shape of vgg_loss input is (n,c,h,w). Maybe you can unsqueeze the render-output before cal vgg_loss.

**Comment by chiehwangs** [comment]
Many people have successfully reproduced the rendering process, so I think there is nothing wrong with the code.

**Comment by saralkun** [comment]
> Hi, when I use your model for training, there report an error: `The size of tensor a (9) must match the size of tensor b (3) at non-singleton dimension 1` ![image](https://private-user-images.githubusercontent.com/140368447/325995739-15bade0f-2441-41f7-ae53-46d35f75c753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTc5MDEsIm5iZiI6MTczNTE5NzYwMSwicGF0aCI6Ii8xNDAzNjg0NDcvMzI1OTk1NzM5LTE1YmFkZTBmLTI0NDEtNDFmNy1hZTUzLTQ2ZDM1Zjc1Yzc1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwNzIwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWJmZGMzOTYzODJjZDliOTIzZjNlNWIzZDcxMTI2MWE3MzM2N2Y5NWFiZDg0ZTk1YmE1ZjM3N2VmMTRhMTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wk2hd__ZfmsDHA4MjD3QMus-BgEOoeRTKEbYGdWtxOY) I wonder if this line of code may be changed from `if input.shape[1] != 3:` to `if input.shape[0] != 3:`? ![image](https://private-user-images.githubusercontent.com/140368447/325994180-b156d2a0-835d-4618-821c-439aa745bcf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTc5MDEsIm5iZiI6MTczNTE5NzYwMSwicGF0aCI6Ii8xNDAzNjg0NDcvMzI1OTk0MTgwLWIxNTZkMmEwLTgzNWQtNDYxOC04MjFjLTQzOWFhNzQ1YmNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwNzIwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjc2ZTMwZjZlYTczYWNhY2I3ZDk2Y2RiMWM1NTZiZjU2NzNlMzM2MDdiOTNiZjMxOGViMGM5MTJhYjZjYTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8Hqk8vMAYtdYgMSOvcWheVqEXZ8XMxWwo1wriR828-E) I really hope you can give me an answer, thank you!

Hello, Could you please share the train.py file?
