### ISSUE TITLE
Cross person reenactment

### ISSUE THREAD

**Issue by Inferencer** [chiehwangs/gaussian-head#5]
Hello I got this working 
I ran
`python render.py -m ./output/id1`
during inference on my 4gb i saw
```
Rendering progress: 100%|██████████████████████████████████████████████████████████| 2254/2254 [49:41<00:00,  1.32s/it]
Rendering progress: 100%|██████████████████████████████████████████████████████████████| 50/50 [01:33<00:00,  1.87s/it]
```
Could you explain what is happening during the above part, due to the duration it took I'm wondering if that's a step that does not need to be repeated?

Also I have the modified dataset downloaded and was wondering if I can do cross identity reenactment with it or if I need to do some training on those persons first?

**Comment by chiehwangs** [comment]
> Hello I got this working I ran `python render.py -m ./output/id1` during inference on my 4gb i saw
> 
> ```
> Rendering progress: 100%|██████████████████████████████████████████████████████████| 2254/2254 [49:41<00:00,  1.32s/it]
> Rendering progress: 100%|██████████████████████████████████████████████████████████████| 50/50 [01:33<00:00,  1.87s/it]
> ```
> 
> Could you explain what is happening during the above part, due to the duration it took I'm wondering if that's a step that does not need to be repeated?
> 
> Also I have the modified dataset downloaded and was wondering if I can do cross identity reenactment with it or if I need to do some training on those persons first?

Firstly, thank you for running the code to understand our work！

1. It will render the complete training and testing data separately, concluding the entire rendering process. 

2. You can utilize other characters within our modified data to drive the id1 avatar without the need for retraining. For instance, if you wish to reenactment id1 using id2, simply replace the facial expressions and c2w parameters in the `dataset_reader.py` with those of id2.

If you need those code, feel free to get in touch with me via email. I'd be more than happy to assist you.
