### ISSUE TITLE
about render

### ISSUE THREAD

**Issue by lakerwe** [chiehwangs/gaussian-head#8]
hey thank you for sharing this wonderful work. i got an error when running   python render.py -m ./output/id1
![image](https://github.com/chiehwangs/gaussian-head/assets/26422814/8b2568b0-1451-47d4-a17f-7d7267ac6eca)
and the \output\id1\point_cloud\iteration_80000 point_cloud is a bee, is that the right pretrained model?

**Comment by chiehwangs** [comment]
> hey thank you for sharing this wonderful work. i got an error when running python render.py -m ./output/id1 ![image](https://private-user-images.githubusercontent.com/26422814/295533515-8b2568b0-1451-47d4-a17f-7d7267ac6eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MzQ3MzIsIm5iZiI6MTcwNDkzNDQzMiwicGF0aCI6Ii8yNjQyMjgxNC8yOTU1MzM1MTUtOGIyNTY4YjAtMTQ1MS00N2Q0LWExN2YtN2Q3MjY3YWM2ZWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAwNTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZjgyMjIyNGZmN2E5OTJiMjE3NzQxNzhmYWZjZGQyMjdiNDk5Y2FhOWE3MzE1MTdjYmZiMzNkMzYyNzI5YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FUDv4GaJrIIfP-L2rOKP1M5Ym_VBgP41eSh_fpZzOZ0) and the \output\id1\point_cloud\iteration_80000 point_cloud is a bee, is that the right pretrained model?

Hi,

`Could not recongnize scene type` may mean that you did not download our dataset, or did not store it according to the path specified by git, [issue](https://github.com/chiehwangs/gaussian-head/issues/4) is worth referencing.
