### ISSUE TITLE
About train.py

### ISSUE THREAD

**Issue by Kedreamix** [chiehwangs/gaussian-head#9]
Thanks for sharing this great work. Hey, just wondering under what conditions you might consider open sourcing the train.py file? I'm really looking forward to being able to train the model on my own dataset.

**Comment by chiehwangs** [comment]
> Thanks for sharing this great work. Hey, just wondering under what conditions you might consider open sourcing the train.py file? I'm really looking forward to being able to train the model on my own dataset.

Thank you for your continued attention!

We will release `train.py` after the review of this job is completed. If you encounter any related questions, you are welcome to contact me via email or issues.

**Comment by Kedreamix** [comment]
Thanks!

**Comment by wynsmile** [comment]
Thank you for your great work and look forward to the release of the training code.
